<?php
/**
 * Autofix registry and runner.
 *
 * Each fix declares:
 *  - id:        unique slug
 *  - label:     human-readable name
 *  - check:     callable returning bool — true if the fix would do something useful
 *  - apply:     callable returning ['status' => 'success'|'error', 'message' => string]
 *
 * Fixes are intentionally narrow in scope. We refuse to mutate user code or
 * touch wp-config.php directly; mu-plugins are used for config-style fixes
 * because they are reversible by deletion and never break the bootstrap.
 *
 * @package WP7ReadinessCheck
 */

declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit;
}

require_once __DIR__ . '/snapshots.php';

/**
 * Drop a small mu-plugin file. Used by config-style fixes.
 * Returns true on write success.
 */
function wp7rc_write_mu_plugin(string $filename, string $contents): bool
{
    $dir = defined('WPMU_PLUGIN_DIR') ? WPMU_PLUGIN_DIR : (WP_CONTENT_DIR . '/mu-plugins');
    if (!is_dir($dir)) {
        if (!@mkdir($dir, 0755, true)) {
            return false;
        }
    }
    if (!is_writable($dir)) {
        return false;
    }
    $target = trailingslashit($dir) . $filename;
    return (bool) @file_put_contents($target, $contents);
}

/**
 * Return the registry of all available fixes.
 *
 * @return array<string, array{label:string,description:string,check:callable,apply:callable}>
 */
function wp7rc_fix_registry(): array
{
    return [

        /* -------------------------------------------------------------
         * FIX: Disable major auto-updates during the 7.0 launch window
         * ------------------------------------------------------------- */
        'disable_major_auto_updates' => [
            'label'       => 'Disable major auto-updates',
            'description' => "Sets WordPress to only auto-update for maintenance and security releases. Major-version updates (like 6.9 → 7.0) require manual approval. Fully reversible from Dashboard → Updates.",
            'check'       => static function (): bool {
                $val = (string) get_site_option('auto_update_core_major', 'unset');
                return $val !== 'disabled';
            },
            'apply'       => static function (): array {
                if (!current_user_can('manage_options')) {
                    return ['status' => 'error', 'message' => 'Permission denied.'];
                }
                update_site_option('auto_update_core_major', 'disabled');
                return ['status' => 'success', 'message' => 'Major auto-updates disabled. Maintenance & security releases will still install automatically.'];
            },
        ],

        /* -------------------------------------------------------------
         * FIX: Disable in-admin file editing (DISALLOW_FILE_EDIT = true)
         * ------------------------------------------------------------- */
        'disallow_file_edit' => [
            'label'       => 'Disable in-admin file editing',
            'description' => "Drops a 5-line mu-plugin defining DISALLOW_FILE_EDIT. Removes the Theme File Editor and Plugin File Editor from Appearance / Plugins. Reversible by deleting wp-content/mu-plugins/champlin-disallow-file-edit.php.",
            'check'       => static function (): bool {
                return !(defined('DISALLOW_FILE_EDIT') && DISALLOW_FILE_EDIT === true);
            },
            'apply'       => static function (): array {
                if (!current_user_can('manage_options')) {
                    return ['status' => 'error', 'message' => 'Permission denied.'];
                }
                $body = "<?php\n"
                      . "/**\n"
                      . " * Plugin Name: Champlin · Disable in-admin file editing\n"
                      . " * Description: Sets DISALLOW_FILE_EDIT for hardened admin. Auto-generated by WP 7 Readiness Check. Delete this file to revert.\n"
                      . " * Version: 1.0.0\n"
                      . " * Author: Champlin Enterprises\n"
                      . " */\n"
                      . "if (!defined('DISALLOW_FILE_EDIT')) {\n"
                      . "    define('DISALLOW_FILE_EDIT', true);\n"
                      . "}\n";
                if (wp7rc_write_mu_plugin('champlin-disallow-file-edit.php', $body)) {
                    return ['status' => 'success', 'message' => 'mu-plugin dropped at wp-content/mu-plugins/champlin-disallow-file-edit.php. In-admin file editing will be blocked on the next page load.'];
                }
                return ['status' => 'error', 'message' => 'Could not write to wp-content/mu-plugins/ — directory may not be writable by the web user.'];
            },
        ],

        /* -------------------------------------------------------------
         * FIX: Update all plugins to their latest stable releases
         * ------------------------------------------------------------- */
        'update_all_plugins' => [
            'label'       => 'Update all plugins',
            'description' => "Installs every pending plugin update — equivalent to clicking 'Update all' on Dashboard → Updates. Idempotent (no-op if nothing pending). Uses WordPress core's own upgrader, so it inherits the same safety guarantees.",
            'check'       => static function (): bool {
                if (!function_exists('get_plugin_updates')) {
                    require_once ABSPATH . 'wp-admin/includes/update.php';
                }
                wp_update_plugins();
                return !empty(get_plugin_updates());
            },
            'apply'       => static function (): array {
                if (!current_user_can('update_plugins')) {
                    return ['status' => 'error', 'message' => 'Permission denied — current user cannot update plugins.'];
                }
                if (!function_exists('get_plugin_updates')) {
                    require_once ABSPATH . 'wp-admin/includes/update.php';
                }
                if (!class_exists('Plugin_Upgrader')) {
                    require_once ABSPATH . 'wp-admin/includes/file.php';
                    require_once ABSPATH . 'wp-admin/includes/misc.php';
                    require_once ABSPATH . 'wp-admin/includes/class-wp-upgrader.php';
                }

                wp_update_plugins();
                $updates = get_plugin_updates();
                if (empty($updates)) {
                    return ['status' => 'success', 'message' => 'All plugins are already up to date.'];
                }

                // SAFETY: snapshot each plugin directory BEFORE the upgrade so the user can
                // restore from wp-content/wp7rc-snapshots/ if a new plugin version breaks the site.
                $snapshot_results = [];
                $snapshot_failed  = [];
                foreach (array_keys($updates) as $plugin_file) {
                    $snap = wp7rc_snapshot_plugin($plugin_file);
                    if (!empty($snap['ok'])) {
                        $snapshot_results[] = $snap['id'];
                    } else {
                        $snapshot_failed[$plugin_file] = $snap['error'] ?? 'unknown error';
                    }
                }
                // If we couldn't snapshot ANY of the plugins, refuse to proceed — the safety net is the point.
                if ($snapshot_results === [] && $snapshot_failed !== []) {
                    return [
                        'status'  => 'error',
                        'message' => 'Refused to update plugins because pre-update snapshots could not be created. Check that wp-content/ is writable by the web user. Errors: ' . implode('; ', array_map(static fn($k, $v) => "$k: $v", array_keys($snapshot_failed), array_values($snapshot_failed))),
                    ];
                }

                $upgrader = new Plugin_Upgrader(new Automatic_Upgrader_Skin());
                $slugs    = array_keys($updates);
                $result   = $upgrader->bulk_upgrade($slugs);

                if (is_wp_error($result)) {
                    return ['status' => 'error', 'message' => 'Upgrade failed: ' . $result->get_error_message()];
                }

                $succeeded = $failed = [];
                foreach ($result as $plugin_file => $r) {
                    if (is_wp_error($r) || $r === false) {
                        $failed[] = $plugin_file;
                    } elseif ($r === true || is_array($r)) {
                        $succeeded[] = $plugin_file;
                    }
                }

                $snap_note = count($snapshot_results) > 0
                    ? sprintf(' Pre-update snapshots taken for %d plugin%s — restore from Snapshots section if needed.', count($snapshot_results), count($snapshot_results) === 1 ? '' : 's')
                    : '';
                if ($failed === []) {
                    return ['status' => 'success', 'message' => sprintf('Updated %d plugin%s successfully.%s', count($succeeded), count($succeeded) === 1 ? '' : 's', $snap_note)];
                }
                return [
                    'status'  => 'error',
                    'message' => sprintf('Updated %d plugin%s; %d failed: %s.%s', count($succeeded), count($succeeded) === 1 ? '' : 's', count($failed), implode(', ', $failed), $snap_note),
                ];
            },
        ],

        /* -------------------------------------------------------------
         * FIX: Install + activate the official Two-Factor plugin
         * ------------------------------------------------------------- */
        'install_two_factor' => [
            'label'       => 'Install Two-Factor plugin',
            'description' => "Installs and activates the official 'Two-Factor' plugin from the WordPress Plugin Directory. After activation, each administrator user configures their preferred 2FA method (TOTP, email, FIDO U2F) under their profile.",
            'check'       => static function (): bool {
                if (!function_exists('get_plugins')) {
                    require_once ABSPATH . 'wp-admin/includes/plugin.php';
                }
                $active   = (array) get_option('active_plugins', []);
                $known_2fa_slugs = ['two-factor/two-factor.php', 'wp-2fa/wp-2fa.php', 'duo-wordpress/duo_wordpress.php', 'miniorange-2-factor-authentication/miniorange_2_factor_settings.php'];
                foreach ($known_2fa_slugs as $slug) {
                    if (in_array($slug, $active, true)) {
                        return false;
                    }
                }
                return true;
            },
            'apply'       => static function (): array {
                if (!current_user_can('install_plugins') || !current_user_can('activate_plugins')) {
                    return ['status' => 'error', 'message' => 'Permission denied — current user cannot install plugins.'];
                }
                if (!class_exists('Plugin_Upgrader')) {
                    require_once ABSPATH . 'wp-admin/includes/file.php';
                    require_once ABSPATH . 'wp-admin/includes/misc.php';
                    require_once ABSPATH . 'wp-admin/includes/plugin-install.php';
                    require_once ABSPATH . 'wp-admin/includes/plugin.php';
                    require_once ABSPATH . 'wp-admin/includes/class-wp-upgrader.php';
                }

                $slug      = 'two-factor';
                $info      = plugins_api('plugin_information', ['slug' => $slug, 'fields' => ['short_description' => false, 'sections' => false]]);
                if (is_wp_error($info)) {
                    return ['status' => 'error', 'message' => 'Could not fetch plugin info from WordPress.org: ' . $info->get_error_message()];
                }

                $upgrader = new Plugin_Upgrader(new Automatic_Upgrader_Skin());
                $installed = $upgrader->install($info->download_link);
                if (is_wp_error($installed)) {
                    return ['status' => 'error', 'message' => 'Install failed: ' . $installed->get_error_message()];
                }

                $plugin_file = 'two-factor/two-factor.php';
                $activate    = activate_plugin($plugin_file);
                if (is_wp_error($activate)) {
                    return ['status' => 'error', 'message' => 'Installed but could not activate: ' . $activate->get_error_message()];
                }
                return ['status' => 'success', 'message' => 'Two-Factor installed and activated. Each administrator now configures 2FA under Users → Profile.'];
            },
        ],

    ];
}

/**
 * Convenience: get a single fix by id.
 */
function wp7rc_fix_get(string $id): ?array
{
    $registry = wp7rc_fix_registry();
    return $registry[$id] ?? null;
}

/**
 * Convenience: is a fix available (applicable + permissions OK)?
 */
function wp7rc_fix_available(string $id): bool
{
    $fix = wp7rc_fix_get($id);
    if ($fix === null) {
        return false;
    }
    try {
        return (bool) ($fix['check'])();
    } catch (\Throwable $e) {
        return false;
    }
}
